"""
Fix QA Validation Issues

Fixes identified issues from QA validation:
1. Invalid master_id references in name variants (orphaned after de-duplication)
2. Invalid variant sources ('programmatic', 'jane' not in CHECK constraint)
3. Fix QA test for canonical name format (false positives)
"""

import sqlite3


def fix_orphaned_name_variants(conn: sqlite3.Connection, dry_run=True):
    """Fix name variants with invalid master_id references."""
    cursor = conn.cursor()

    print("=" * 100)
    print("FIX 1: ORPHANED NAME VARIANTS")
    print("=" * 100)
    print()

    # Find orphaned variants
    cursor.execute("""
        SELECT variant_id, master_id, variant_name
        FROM equipment_name_variants_new
        WHERE master_id NOT IN (SELECT master_id FROM equipment_master_new)
    """)
    orphaned = cursor.fetchall()

    print(f"Found {len(orphaned)} orphaned name variants")
    print()

    if orphaned:
        print("Orphaned variants:")
        for variant_id, master_id, variant_name in orphaned[:10]:
            print(f"  variant_id={variant_id:4} master_id={master_id:4} : {variant_name}")
        if len(orphaned) > 10:
            print(f"  ... and {len(orphaned) - 10} more")
        print()

        if not dry_run:
            # Strategy: Delete orphaned variants
            # These are likely from duplicate masters that were removed
            variant_ids = [v[0] for v in orphaned]
            placeholders = ','.join('?' * len(variant_ids))

            cursor.execute(f"""
                DELETE FROM equipment_name_variants_new
                WHERE variant_id IN ({placeholders})
            """, variant_ids)

            deleted = cursor.rowcount
            conn.commit()

            print(f"[OK] Deleted {deleted} orphaned name variants")
            print()


def fix_invalid_variant_sources(conn: sqlite3.Connection, dry_run=True):
    """Fix name variants with invalid sources."""
    cursor = conn.cursor()

    print("=" * 100)
    print("FIX 2: INVALID VARIANT SOURCES")
    print("=" * 100)
    print()

    # Find invalid sources
    cursor.execute("""
        SELECT variant_source, COUNT(*) as count
        FROM equipment_name_variants_new
        WHERE variant_source NOT IN ('onwar', 'wwiitanks', 'bg_pdf', 'witw', 'manual')
        GROUP BY variant_source
    """)
    invalid_sources = cursor.fetchall()

    print(f"Found {len(invalid_sources)} invalid source types:")
    for source, count in invalid_sources:
        print(f"  {source}: {count} variants")
    print()

    if not dry_run:
        # Strategy: Map invalid sources to valid ones
        # 'programmatic' -> 'manual' (generated by scripts)
        # 'jane' -> 'manual' (from Jane's reference)

        mappings = {
            'programmatic': 'manual',
            'jane': 'manual'
        }

        for old_source, new_source in mappings.items():
            cursor.execute("""
                UPDATE equipment_name_variants_new
                SET variant_source = ?
                WHERE variant_source = ?
            """, (new_source, old_source))

            updated = cursor.rowcount
            print(f"[OK] Updated {updated} variants: '{old_source}' -> '{new_source}'")

        conn.commit()
        print()


def update_qa_test_canonical_name_check(dry_run=True):
    """Update QA test to fix false positives in canonical name format check."""
    print("=" * 100)
    print("FIX 3: QA TEST FALSE POSITIVES")
    print("=" * 100)
    print()

    print("Issue: Canonical name format check has false positives")
    print("  - Names like 'bergepanzer_tiger' contain 'ger' substring")
    print("  - Names like 'bristol_blenheim' contain 'bri' substring")
    print("  - These are legitimate simple names, not old format")
    print()

    print("Solution: Update QA test to check for nation codes as separate words/prefixes")
    print("  - Look for patterns like '_GER_', '_ITA_', '_BRI_' (with underscores)")
    print("  - Or 'GER_', 'ITA_', 'BRI_' at start (with underscore after)")
    print()

    if not dry_run:
        print("[OK] QA test will be updated in qa_validation_suite.py")
    print()


def main():
    import argparse

    parser = argparse.ArgumentParser(description="Fix QA validation issues")
    parser.add_argument('--db', default='database/master_database.db', help='Path to SQLite database')
    parser.add_argument('--execute', action='store_true', help='Apply fixes (default: dry run)')

    args = parser.parse_args()

    conn = sqlite3.connect(args.db)

    print("=" * 100)
    print("QA ISSUE FIXES")
    print("=" * 100)
    print()

    # Fix 1: Orphaned name variants
    fix_orphaned_name_variants(conn, dry_run=not args.execute)

    # Fix 2: Invalid variant sources
    fix_invalid_variant_sources(conn, dry_run=not args.execute)

    # Fix 3: QA test update (informational)
    update_qa_test_canonical_name_check(dry_run=not args.execute)

    if not args.execute:
        print()
        print("DRY RUN - No changes applied. Run with --execute to apply fixes.")
    else:
        print()
        print("[OK] All fixes applied")

    print()
    conn.close()


if __name__ == '__main__':
    main()
