-- Tier 3: Base Model Matches SQL Script
-- Generated by tier3_base_model.py
-- Applies base model matching (variant tolerance)

BEGIN TRANSACTION;

-- Match 1/26: Jeep Command → Jeep
--   Base model: jeep (distance: 2)
UPDATE equipment_battlegroup
SET reference_vehicle_id = 244,
    reference_match_confidence = 80
WHERE equipment_id = 'USA_JEEP_COMMAND';

-- Log to audit
INSERT INTO normalization_audit (operation, table_name, record_id, old_value, new_value, reason, timestamp)
VALUES ('UPDATE', 'equipment_battlegroup', 'USA_JEEP_COMMAND', 'NULL', '244', 'Tier 3: base_model (dist=2)', datetime('now'));

-- Match 2/26: M3 Lee → M3 Lee
--   Base model: m3 lee (distance: 0)
UPDATE equipment_battlegroup
SET reference_vehicle_id = 233,
    reference_match_confidence = 80
WHERE equipment_id = 'USA_M3_LEE';

-- Log to audit
INSERT INTO normalization_audit (operation, table_name, record_id, old_value, new_value, reason, timestamp)
VALUES ('UPDATE', 'equipment_battlegroup', 'USA_M3_LEE', 'NULL', '233', 'Tier 3: base_model (dist=0)', datetime('now'));

-- Match 3/26: M4 Sherman → M4 Sherman
--   Base model: m4 sherman (distance: 0)
UPDATE equipment_battlegroup
SET reference_vehicle_id = 203,
    reference_match_confidence = 80
WHERE equipment_id = 'USA_M4_SHERMAN';

-- Log to audit
INSERT INTO normalization_audit (operation, table_name, record_id, old_value, new_value, reason, timestamp)
VALUES ('UPDATE', 'equipment_battlegroup', 'USA_M4_SHERMAN', 'NULL', '203', 'Tier 3: base_model_variants (dist=0)', datetime('now'));

-- Match 4/26: M8 Greyhound → M8 Greyhound
--   Base model: m8 greyhound (distance: 0)
UPDATE equipment_battlegroup
SET reference_vehicle_id = 242,
    reference_match_confidence = 80
WHERE equipment_id = 'USA_M8_GREYHOUND';

-- Log to audit
INSERT INTO normalization_audit (operation, table_name, record_id, old_value, new_value, reason, timestamp)
VALUES ('UPDATE', 'equipment_battlegroup', 'USA_M8_GREYHOUND', 'NULL', '242', 'Tier 3: base_model (dist=0)', datetime('now'));

-- Match 5/26: A10 Cruiser → A10 Cruiser
--   Base model: a10 cruiser (distance: 0)
UPDATE equipment_battlegroup
SET reference_vehicle_id = 294,
    reference_match_confidence = 80
WHERE equipment_id = 'GBR_A10_CRUISER';

-- Log to audit
INSERT INTO normalization_audit (operation, table_name, record_id, old_value, new_value, reason, timestamp)
VALUES ('UPDATE', 'equipment_battlegroup', 'GBR_A10_CRUISER', 'NULL', '294', 'Tier 3: base_model (dist=0)', datetime('now'));

-- Match 6/26: A10 Cruiser Mk II → A10 Cruiser
--   Base model: a10 cruiser (distance: 2)
UPDATE equipment_battlegroup
SET reference_vehicle_id = 294,
    reference_match_confidence = 80
WHERE equipment_id = 'GBR_A10_CRUISER_MK_II';

-- Log to audit
INSERT INTO normalization_audit (operation, table_name, record_id, old_value, new_value, reason, timestamp)
VALUES ('UPDATE', 'equipment_battlegroup', 'GBR_A10_CRUISER_MK_II', 'NULL', '294', 'Tier 3: base_model (dist=2)', datetime('now'));

-- Match 7/26: A13 Cruiser → A13 Mk I Cruiser
--   Base model: a13 cruiser (distance: 2)
UPDATE equipment_battlegroup
SET reference_vehicle_id = 295,
    reference_match_confidence = 80
WHERE equipment_id = 'GBR_A13_CRUISER';

-- Log to audit
INSERT INTO normalization_audit (operation, table_name, record_id, old_value, new_value, reason, timestamp)
VALUES ('UPDATE', 'equipment_battlegroup', 'GBR_A13_CRUISER', 'NULL', '295', 'Tier 3: base_model (dist=2)', datetime('now'));

-- Match 8/26: A13 Cruiser Mk IV → A13 Mk I Cruiser
--   Base model: a13 cruiser (distance: 1)
UPDATE equipment_battlegroup
SET reference_vehicle_id = 295,
    reference_match_confidence = 80
WHERE equipment_id = 'GBR_A13_CRUISER_MK_IV';

-- Log to audit
INSERT INTO normalization_audit (operation, table_name, record_id, old_value, new_value, reason, timestamp)
VALUES ('UPDATE', 'equipment_battlegroup', 'GBR_A13_CRUISER_MK_IV', 'NULL', '295', 'Tier 3: base_model (dist=1)', datetime('now'));

-- Match 9/26: A13 Mk II Cruiser → A13 Mk I Cruiser
--   Base model: a13 cruiser (distance: 1)
UPDATE equipment_battlegroup
SET reference_vehicle_id = 295,
    reference_match_confidence = 80
WHERE equipment_id = 'GBR_A13_MK_II_CRUISER';

-- Log to audit
INSERT INTO normalization_audit (operation, table_name, record_id, old_value, new_value, reason, timestamp)
VALUES ('UPDATE', 'equipment_battlegroup', 'GBR_A13_MK_II_CRUISER', 'NULL', '295', 'Tier 3: base_model (dist=1)', datetime('now'));

-- Match 10/26: A9 Cruiser → A9 Cruiser
--   Base model: a9 cruiser (distance: 0)
UPDATE equipment_battlegroup
SET reference_vehicle_id = 292,
    reference_match_confidence = 80
WHERE equipment_id = 'GBR_A9_CRUISER';

-- Log to audit
INSERT INTO normalization_audit (operation, table_name, record_id, old_value, new_value, reason, timestamp)
VALUES ('UPDATE', 'equipment_battlegroup', 'GBR_A9_CRUISER', 'NULL', '292', 'Tier 3: base_model (dist=0)', datetime('now'));

-- Match 11/26: A9 Cruiser Mk I → A9 Cruiser
--   Base model: a9 cruiser (distance: 2)
UPDATE equipment_battlegroup
SET reference_vehicle_id = 292,
    reference_match_confidence = 80
WHERE equipment_id = 'GBR_A9_CRUISER_MK_I';

-- Log to audit
INSERT INTO normalization_audit (operation, table_name, record_id, old_value, new_value, reason, timestamp)
VALUES ('UPDATE', 'equipment_battlegroup', 'GBR_A9_CRUISER_MK_I', 'NULL', '292', 'Tier 3: base_model (dist=2)', datetime('now'));

-- Match 12/26: Churchill VII → Churchill VII
--   Base model: churchill vii (distance: 0)
UPDATE equipment_battlegroup
SET reference_vehicle_id = 344,
    reference_match_confidence = 80
WHERE equipment_id = 'GBR_CHURCHILL_VII';

-- Log to audit
INSERT INTO normalization_audit (operation, table_name, record_id, old_value, new_value, reason, timestamp)
VALUES ('UPDATE', 'equipment_battlegroup', 'GBR_CHURCHILL_VII', 'NULL', '344', 'Tier 3: base_model (dist=0)', datetime('now'));

-- Match 13/26: Daimler Mk I → Daimler
--   Base model: daimler (distance: 2)
UPDATE equipment_battlegroup
SET reference_vehicle_id = 330,
    reference_match_confidence = 80
WHERE equipment_id = 'GBR_DAIMLER_MK_I';

-- Log to audit
INSERT INTO normalization_audit (operation, table_name, record_id, old_value, new_value, reason, timestamp)
VALUES ('UPDATE', 'equipment_battlegroup', 'GBR_DAIMLER_MK_I', 'NULL', '330', 'Tier 3: base_model (dist=2)', datetime('now'));

-- Match 14/26: Humber Scout Car → Humber Scout Car
--   Base model: humber scout car (distance: 0)
UPDATE equipment_battlegroup
SET reference_vehicle_id = 334,
    reference_match_confidence = 80
WHERE equipment_id = 'GBR_HUMBER_SCOUT_CAR';

-- Log to audit
INSERT INTO normalization_audit (operation, table_name, record_id, old_value, new_value, reason, timestamp)
VALUES ('UPDATE', 'equipment_battlegroup', 'GBR_HUMBER_SCOUT_CAR', 'NULL', '334', 'Tier 3: base_model (dist=0)', datetime('now'));

-- Match 15/26: Matilda II → Matilda II
--   Base model: matilda ii (distance: 0)
UPDATE equipment_battlegroup
SET reference_vehicle_id = 290,
    reference_match_confidence = 80
WHERE equipment_id = 'GBR_MATILDA_II';

-- Log to audit
INSERT INTO normalization_audit (operation, table_name, record_id, old_value, new_value, reason, timestamp)
VALUES ('UPDATE', 'equipment_battlegroup', 'GBR_MATILDA_II', 'NULL', '290', 'Tier 3: base_model (dist=0)', datetime('now'));

-- Match 16/26: Morris Quad → Morris Quad
--   Base model: morris quad (distance: 0)
UPDATE equipment_battlegroup
SET reference_vehicle_id = 446,
    reference_match_confidence = 80
WHERE equipment_id = 'GBR_MORRIS_QUAD';

-- Log to audit
INSERT INTO normalization_audit (operation, table_name, record_id, old_value, new_value, reason, timestamp)
VALUES ('UPDATE', 'equipment_battlegroup', 'GBR_MORRIS_QUAD', 'NULL', '446', 'Tier 3: base_model (dist=0)', datetime('now'));

-- Match 17/26: Tetrarch Mk VII → Tetrarch
--   Base model: tetrarch (distance: 2)
UPDATE equipment_battlegroup
SET reference_vehicle_id = 313,
    reference_match_confidence = 80
WHERE equipment_id = 'GBR_TETRARCH_MK_VII';

-- Log to audit
INSERT INTO normalization_audit (operation, table_name, record_id, old_value, new_value, reason, timestamp)
VALUES ('UPDATE', 'equipment_battlegroup', 'GBR_TETRARCH_MK_VII', 'NULL', '313', 'Tier 3: base_model (dist=2)', datetime('now'));

-- Match 18/26: Panzer I Ausf A → Panzer I
--   Base model: panzer i (distance: 2)
UPDATE equipment_battlegroup
SET reference_vehicle_id = 355,
    reference_match_confidence = 80
WHERE equipment_id = 'GER_PANZER_I_AUSF_A';

-- Log to audit
INSERT INTO normalization_audit (operation, table_name, record_id, old_value, new_value, reason, timestamp)
VALUES ('UPDATE', 'equipment_battlegroup', 'GER_PANZER_I_AUSF_A', 'NULL', '355', 'Tier 3: base_model (dist=2)', datetime('now'));

-- Match 19/26: Panzer I Ausf B → Panzer I
--   Base model: panzer i (distance: 2)
UPDATE equipment_battlegroup
SET reference_vehicle_id = 355,
    reference_match_confidence = 80
WHERE equipment_id = 'GER_PANZER_I_AUSF_B';

-- Log to audit
INSERT INTO normalization_audit (operation, table_name, record_id, old_value, new_value, reason, timestamp)
VALUES ('UPDATE', 'equipment_battlegroup', 'GER_PANZER_I_AUSF_B', 'NULL', '355', 'Tier 3: base_model (dist=2)', datetime('now'));

-- Match 20/26: SdKfz 222 → SdKfz 222
--   Base model: sdkfz 222 (distance: 0)
UPDATE equipment_battlegroup
SET reference_vehicle_id = 20,
    reference_match_confidence = 80
WHERE equipment_id = 'GER_SDKFZ_222';

-- Log to audit
INSERT INTO normalization_audit (operation, table_name, record_id, old_value, new_value, reason, timestamp)
VALUES ('UPDATE', 'equipment_battlegroup', 'GER_SDKFZ_222', 'NULL', '20', 'Tier 3: base_model_variants (dist=0)', datetime('now'));

-- Match 21/26: SdKfz 223 → SdKfz 223
--   Base model: sdkfz 223 (distance: 0)
UPDATE equipment_battlegroup
SET reference_vehicle_id = 378,
    reference_match_confidence = 80
WHERE equipment_id = 'GER_SDKFZ_223';

-- Log to audit
INSERT INTO normalization_audit (operation, table_name, record_id, old_value, new_value, reason, timestamp)
VALUES ('UPDATE', 'equipment_battlegroup', 'GER_SDKFZ_223', 'NULL', '378', 'Tier 3: base_model (dist=0)', datetime('now'));

-- Match 22/26: SdKfz 231 → SdKfz 231
--   Base model: sdkfz 231 (distance: 0)
UPDATE equipment_battlegroup
SET reference_vehicle_id = 380,
    reference_match_confidence = 80
WHERE equipment_id = 'GER_SDKFZ_231';

-- Log to audit
INSERT INTO normalization_audit (operation, table_name, record_id, old_value, new_value, reason, timestamp)
VALUES ('UPDATE', 'equipment_battlegroup', 'GER_SDKFZ_231', 'NULL', '380', 'Tier 3: base_model (dist=0)', datetime('now'));

-- Match 23/26: SdKfz 250 → SdKfz 250
--   Base model: sdkfz 250 (distance: 0)
UPDATE equipment_battlegroup
SET reference_vehicle_id = 386,
    reference_match_confidence = 80
WHERE equipment_id = 'GER_SDKFZ_250';

-- Log to audit
INSERT INTO normalization_audit (operation, table_name, record_id, old_value, new_value, reason, timestamp)
VALUES ('UPDATE', 'equipment_battlegroup', 'GER_SDKFZ_250', 'NULL', '386', 'Tier 3: base_model (dist=0)', datetime('now'));

-- Match 24/26: SdKfz 251/1 → SdKfz 251/1
--   Base model: sdkfz 251/1 (distance: 0)
UPDATE equipment_battlegroup
SET reference_vehicle_id = 23,
    reference_match_confidence = 80
WHERE equipment_id = 'GER_SDKFZ_251_1';

-- Log to audit
INSERT INTO normalization_audit (operation, table_name, record_id, old_value, new_value, reason, timestamp)
VALUES ('UPDATE', 'equipment_battlegroup', 'GER_SDKFZ_251_1', 'NULL', '23', 'Tier 3: base_model_variants (dist=0)', datetime('now'));

-- Match 25/26: SdKfz 251/2 → SdKfz 251/2
--   Base model: sdkfz 251/2 (distance: 0)
UPDATE equipment_battlegroup
SET reference_vehicle_id = 24,
    reference_match_confidence = 80
WHERE equipment_id = 'GER_SDKFZ_251_2';

-- Log to audit
INSERT INTO normalization_audit (operation, table_name, record_id, old_value, new_value, reason, timestamp)
VALUES ('UPDATE', 'equipment_battlegroup', 'GER_SDKFZ_251_2', 'NULL', '24', 'Tier 3: base_model_variants (dist=0)', datetime('now'));

-- Match 26/26: SdKfz 251/3 → SdKfz 251/3
--   Base model: sdkfz 251/3 (distance: 0)
UPDATE equipment_battlegroup
SET reference_vehicle_id = 25,
    reference_match_confidence = 80
WHERE equipment_id = 'GER_SDKFZ_251_3';

-- Log to audit
INSERT INTO normalization_audit (operation, table_name, record_id, old_value, new_value, reason, timestamp)
VALUES ('UPDATE', 'equipment_battlegroup', 'GER_SDKFZ_251_3', 'NULL', '25', 'Tier 3: base_model_variants (dist=0)', datetime('now'));

-- Validation
SELECT COUNT(*) as tier3_conf80 FROM equipment_battlegroup WHERE reference_match_confidence = 80;
-- Expected: 26

SELECT COUNT(*) as tier3_conf75 FROM equipment_battlegroup WHERE reference_match_confidence = 75;
-- Expected: 0

COMMIT;

-- Rollback if needed:
-- ROLLBACK;