-- Tier 2: Normalized Matches SQL Script
-- Generated by tier2_normalization.py
-- Applies normalization-based equipment linkage

BEGIN TRANSACTION;

-- Validate starting state
SELECT COUNT(*) as tier2_candidates FROM equipment_battlegroup WHERE reference_vehicle_id IS NULL;

-- Match 1/18: Lee M3 → M3 Lee
UPDATE equipment_battlegroup
SET reference_vehicle_id = 233,
    reference_match_confidence = 85
WHERE equipment_id = 'USA_LEE_M3';

-- Log to audit
INSERT INTO normalization_audit (operation, table_name, record_id, old_value, new_value, reason, timestamp)
VALUES ('UPDATE', 'equipment_battlegroup', 'USA_LEE_M3', 'NULL', '233', 'Tier 2: reverse_order', datetime('now'));

-- Match 2/18: M3 Lee → M3 Lee
UPDATE equipment_battlegroup
SET reference_vehicle_id = 233,
    reference_match_confidence = 90
WHERE equipment_id = 'USA_M3_LEE';

-- Log to audit
INSERT INTO normalization_audit (operation, table_name, record_id, old_value, new_value, reason, timestamp)
VALUES ('UPDATE', 'equipment_battlegroup', 'USA_M3_LEE', 'NULL', '233', 'Tier 2: normalized', datetime('now'));

-- Match 3/18: M4 Sherman → M4 Sherman
UPDATE equipment_battlegroup
SET reference_vehicle_id = 203,
    reference_match_confidence = 90
WHERE equipment_id = 'USA_M4_SHERMAN';

-- Log to audit
INSERT INTO normalization_audit (operation, table_name, record_id, old_value, new_value, reason, timestamp)
VALUES ('UPDATE', 'equipment_battlegroup', 'USA_M4_SHERMAN', 'NULL', '203', 'Tier 2: normalized', datetime('now'));

-- Match 4/18: M8 Greyhound → M8 Greyhound
UPDATE equipment_battlegroup
SET reference_vehicle_id = 242,
    reference_match_confidence = 90
WHERE equipment_id = 'USA_M8_GREYHOUND';

-- Log to audit
INSERT INTO normalization_audit (operation, table_name, record_id, old_value, new_value, reason, timestamp)
VALUES ('UPDATE', 'equipment_battlegroup', 'USA_M8_GREYHOUND', 'NULL', '242', 'Tier 2: normalized', datetime('now'));

-- Match 5/18: Sherman M4 → M4 Sherman
UPDATE equipment_battlegroup
SET reference_vehicle_id = 203,
    reference_match_confidence = 85
WHERE equipment_id = 'USA_SHERMAN_M4';

-- Log to audit
INSERT INTO normalization_audit (operation, table_name, record_id, old_value, new_value, reason, timestamp)
VALUES ('UPDATE', 'equipment_battlegroup', 'USA_SHERMAN_M4', 'NULL', '203', 'Tier 2: reverse_order', datetime('now'));

-- Match 6/18: A10 Cruiser → A10 Cruiser
UPDATE equipment_battlegroup
SET reference_vehicle_id = 294,
    reference_match_confidence = 90
WHERE equipment_id = 'GBR_A10_CRUISER';

-- Log to audit
INSERT INTO normalization_audit (operation, table_name, record_id, old_value, new_value, reason, timestamp)
VALUES ('UPDATE', 'equipment_battlegroup', 'GBR_A10_CRUISER', 'NULL', '294', 'Tier 2: normalized', datetime('now'));

-- Match 7/18: A9 Cruiser → A9 Cruiser
UPDATE equipment_battlegroup
SET reference_vehicle_id = 292,
    reference_match_confidence = 90
WHERE equipment_id = 'GBR_A9_CRUISER';

-- Log to audit
INSERT INTO normalization_audit (operation, table_name, record_id, old_value, new_value, reason, timestamp)
VALUES ('UPDATE', 'equipment_battlegroup', 'GBR_A9_CRUISER', 'NULL', '292', 'Tier 2: normalized', datetime('now'));

-- Match 8/18: Churchill VII → Churchill VII
UPDATE equipment_battlegroup
SET reference_vehicle_id = 344,
    reference_match_confidence = 90
WHERE equipment_id = 'GBR_CHURCHILL_VII';

-- Log to audit
INSERT INTO normalization_audit (operation, table_name, record_id, old_value, new_value, reason, timestamp)
VALUES ('UPDATE', 'equipment_battlegroup', 'GBR_CHURCHILL_VII', 'NULL', '344', 'Tier 2: normalized', datetime('now'));

-- Match 9/18: Humber Scout Car → Humber Scout Car
UPDATE equipment_battlegroup
SET reference_vehicle_id = 334,
    reference_match_confidence = 90
WHERE equipment_id = 'GBR_HUMBER_SCOUT_CAR';

-- Log to audit
INSERT INTO normalization_audit (operation, table_name, record_id, old_value, new_value, reason, timestamp)
VALUES ('UPDATE', 'equipment_battlegroup', 'GBR_HUMBER_SCOUT_CAR', 'NULL', '334', 'Tier 2: normalized', datetime('now'));

-- Match 10/18: Matilda II → Matilda II
UPDATE equipment_battlegroup
SET reference_vehicle_id = 290,
    reference_match_confidence = 90
WHERE equipment_id = 'GBR_MATILDA_II';

-- Log to audit
INSERT INTO normalization_audit (operation, table_name, record_id, old_value, new_value, reason, timestamp)
VALUES ('UPDATE', 'equipment_battlegroup', 'GBR_MATILDA_II', 'NULL', '290', 'Tier 2: normalized', datetime('now'));

-- Match 11/18: Morris Quad → Morris Quad
UPDATE equipment_battlegroup
SET reference_vehicle_id = 446,
    reference_match_confidence = 90
WHERE equipment_id = 'GBR_MORRIS_QUAD';

-- Log to audit
INSERT INTO normalization_audit (operation, table_name, record_id, old_value, new_value, reason, timestamp)
VALUES ('UPDATE', 'equipment_battlegroup', 'GBR_MORRIS_QUAD', 'NULL', '446', 'Tier 2: normalized', datetime('now'));

-- Match 12/18: SdKfz 222 → SdKfz 222
UPDATE equipment_battlegroup
SET reference_vehicle_id = 20,
    reference_match_confidence = 90
WHERE equipment_id = 'GER_SDKFZ_222';

-- Log to audit
INSERT INTO normalization_audit (operation, table_name, record_id, old_value, new_value, reason, timestamp)
VALUES ('UPDATE', 'equipment_battlegroup', 'GER_SDKFZ_222', 'NULL', '20', 'Tier 2: normalized', datetime('now'));

-- Match 13/18: SdKfz 223 → SdKfz 223
UPDATE equipment_battlegroup
SET reference_vehicle_id = 378,
    reference_match_confidence = 90
WHERE equipment_id = 'GER_SDKFZ_223';

-- Log to audit
INSERT INTO normalization_audit (operation, table_name, record_id, old_value, new_value, reason, timestamp)
VALUES ('UPDATE', 'equipment_battlegroup', 'GER_SDKFZ_223', 'NULL', '378', 'Tier 2: normalized', datetime('now'));

-- Match 14/18: SdKfz 231 → SdKfz 231
UPDATE equipment_battlegroup
SET reference_vehicle_id = 380,
    reference_match_confidence = 90
WHERE equipment_id = 'GER_SDKFZ_231';

-- Log to audit
INSERT INTO normalization_audit (operation, table_name, record_id, old_value, new_value, reason, timestamp)
VALUES ('UPDATE', 'equipment_battlegroup', 'GER_SDKFZ_231', 'NULL', '380', 'Tier 2: normalized', datetime('now'));

-- Match 15/18: SdKfz 250 → SdKfz 250
UPDATE equipment_battlegroup
SET reference_vehicle_id = 386,
    reference_match_confidence = 90
WHERE equipment_id = 'GER_SDKFZ_250';

-- Log to audit
INSERT INTO normalization_audit (operation, table_name, record_id, old_value, new_value, reason, timestamp)
VALUES ('UPDATE', 'equipment_battlegroup', 'GER_SDKFZ_250', 'NULL', '386', 'Tier 2: normalized', datetime('now'));

-- Match 16/18: SdKfz 251/1 → SdKfz 251/1
UPDATE equipment_battlegroup
SET reference_vehicle_id = 23,
    reference_match_confidence = 90
WHERE equipment_id = 'GER_SDKFZ_251_1';

-- Log to audit
INSERT INTO normalization_audit (operation, table_name, record_id, old_value, new_value, reason, timestamp)
VALUES ('UPDATE', 'equipment_battlegroup', 'GER_SDKFZ_251_1', 'NULL', '23', 'Tier 2: normalized', datetime('now'));

-- Match 17/18: SdKfz 251/2 → SdKfz 251/2
UPDATE equipment_battlegroup
SET reference_vehicle_id = 24,
    reference_match_confidence = 90
WHERE equipment_id = 'GER_SDKFZ_251_2';

-- Log to audit
INSERT INTO normalization_audit (operation, table_name, record_id, old_value, new_value, reason, timestamp)
VALUES ('UPDATE', 'equipment_battlegroup', 'GER_SDKFZ_251_2', 'NULL', '24', 'Tier 2: normalized', datetime('now'));

-- Match 18/18: SdKfz 251/3 → SdKfz 251/3
UPDATE equipment_battlegroup
SET reference_vehicle_id = 25,
    reference_match_confidence = 90
WHERE equipment_id = 'GER_SDKFZ_251_3';

-- Log to audit
INSERT INTO normalization_audit (operation, table_name, record_id, old_value, new_value, reason, timestamp)
VALUES ('UPDATE', 'equipment_battlegroup', 'GER_SDKFZ_251_3', 'NULL', '25', 'Tier 2: normalized', datetime('now'));

-- Validation: Check matches applied
SELECT COUNT(*) as tier2_applied FROM equipment_battlegroup WHERE reference_match_confidence = 90;
-- Expected: 16

SELECT COUNT(*) as tier2_reverse FROM equipment_battlegroup WHERE reference_match_confidence = 85;
-- Expected: 2

-- If validation passes:
COMMIT;

-- If validation fails, rollback:
-- ROLLBACK;