-- Tier 3: Base Model Matches SQL Script
-- Generated by tier3_base_model.py
-- Applies base model matching (variant tolerance)

BEGIN TRANSACTION;

-- Validation
SELECT COUNT(*) as tier3_conf80 FROM equipment_battlegroup WHERE reference_match_confidence = 80;
-- Expected: 0

SELECT COUNT(*) as tier3_conf75 FROM equipment_battlegroup WHERE reference_match_confidence = 75;
-- Expected: 0

COMMIT;

-- Rollback if needed:
-- ROLLBACK;