-- Tier 4: Artillery/Gun Linkage SQL Script
-- Generated by tier4_artillery_linkage.py
-- Links artillery to bg_reference_guns via reference_gun_id

BEGIN TRANSACTION;

-- Match 1/16: 105mm M2A1 → 105mmL16
--   Caliber: 105mm
UPDATE equipment_battlegroup
SET reference_gun_id = 46,
    reference_gun_match_confidence = 90
WHERE equipment_id = 'USA_105MM_M2A1';

-- Audit log
INSERT INTO normalization_audit (operation, table_name, record_id, old_value, new_value, reason, timestamp)
VALUES ('UPDATE', 'equipment_battlegroup', 'USA_105MM_M2A1', 'NULL', '46', 'Tier 4: nation_caliber', datetime('now'));

-- Match 2/16: 57mm M1 → 57mmL46
--   Caliber: 57mm
UPDATE equipment_battlegroup
SET reference_gun_id = 44,
    reference_gun_match_confidence = 90
WHERE equipment_id = 'USA_57MM_M1';

-- Audit log
INSERT INTO normalization_audit (operation, table_name, record_id, old_value, new_value, reason, timestamp)
VALUES ('UPDATE', 'equipment_battlegroup', 'USA_57MM_M1', 'NULL', '44', 'Tier 4: nation_caliber', datetime('now'));

-- Match 3/16: M1 57mm AT Gun → 57mmL46
--   Caliber: 57mm
UPDATE equipment_battlegroup
SET reference_gun_id = 44,
    reference_gun_match_confidence = 90
WHERE equipment_id = 'USA_M1_57MM_AT_GUN';

-- Audit log
INSERT INTO normalization_audit (operation, table_name, record_id, old_value, new_value, reason, timestamp)
VALUES ('UPDATE', 'equipment_battlegroup', 'USA_M1_57MM_AT_GUN', 'NULL', '44', 'Tier 4: nation_caliber', datetime('now'));

-- Match 4/16: M1 81mm Mortar → 81mm mortar
--   Caliber: 81mm
UPDATE equipment_battlegroup
SET reference_gun_id = 43,
    reference_gun_match_confidence = 90
WHERE equipment_id = 'USA_M1_81MM_MORTAR';

-- Audit log
INSERT INTO normalization_audit (operation, table_name, record_id, old_value, new_value, reason, timestamp)
VALUES ('UPDATE', 'equipment_battlegroup', 'USA_M1_81MM_MORTAR', 'NULL', '43', 'Tier 4: nation_caliber', datetime('now'));

-- Match 5/16: M2A1 105mm Howitzer → 105mmL16
--   Caliber: 105mm
UPDATE equipment_battlegroup
SET reference_gun_id = 46,
    reference_gun_match_confidence = 90
WHERE equipment_id = 'USA_M2A1_105MM_HOWITZER';

-- Audit log
INSERT INTO normalization_audit (operation, table_name, record_id, old_value, new_value, reason, timestamp)
VALUES ('UPDATE', 'equipment_battlegroup', 'USA_M2A1_105MM_HOWITZER', 'NULL', '46', 'Tier 4: nation_caliber', datetime('now'));

-- Match 6/16: 20mm Oerlikon → 20mm Polsten
--   Caliber: 20mm
UPDATE equipment_battlegroup
SET reference_gun_id = 37,
    reference_gun_match_confidence = 90
WHERE equipment_id = 'GBR_20MM_OERLIKON';

-- Audit log
INSERT INTO normalization_audit (operation, table_name, record_id, old_value, new_value, reason, timestamp)
VALUES ('UPDATE', 'equipment_battlegroup', 'GBR_20MM_OERLIKON', 'NULL', '37', 'Tier 4: nation_caliber', datetime('now'));

-- Match 7/16: 6 Pdr AT → 6 pdr
--   Caliber: 57mm
UPDATE equipment_battlegroup
SET reference_gun_id = 32,
    reference_gun_match_confidence = 90
WHERE equipment_id = 'GBR_6_PDR_AT';

-- Audit log
INSERT INTO normalization_audit (operation, table_name, record_id, old_value, new_value, reason, timestamp)
VALUES ('UPDATE', 'equipment_battlegroup', 'GBR_6_PDR_AT', 'NULL', '32', 'Tier 4: nation_caliber', datetime('now'));

-- Match 8/16: 6 Pounder → 6 pdr
--   Caliber: 57mm
UPDATE equipment_battlegroup
SET reference_gun_id = 32,
    reference_gun_match_confidence = 90
WHERE equipment_id = 'GBR_6_POUNDER';

-- Audit log
INSERT INTO normalization_audit (operation, table_name, record_id, old_value, new_value, reason, timestamp)
VALUES ('UPDATE', 'equipment_battlegroup', 'GBR_6_POUNDER', 'NULL', '32', 'Tier 4: nation_caliber', datetime('now'));

-- Match 9/16: Oerlikon 20mm → 20mm Polsten
--   Caliber: 20mm
UPDATE equipment_battlegroup
SET reference_gun_id = 37,
    reference_gun_match_confidence = 90
WHERE equipment_id = 'GBR_OERLIKON_20MM';

-- Audit log
INSERT INTO normalization_audit (operation, table_name, record_id, old_value, new_value, reason, timestamp)
VALUES ('UPDATE', 'equipment_battlegroup', 'GBR_OERLIKON_20MM', 'NULL', '37', 'Tier 4: nation_caliber', datetime('now'));

-- Match 10/16: Ordnance QF 6-pounder Mk V → 6 pdr
--   Caliber: 57mm
UPDATE equipment_battlegroup
SET reference_gun_id = 32,
    reference_gun_match_confidence = 90
WHERE equipment_id = 'GBR_ORDNANCE_QF_6-POUNDER_MK_V';

-- Audit log
INSERT INTO normalization_audit (operation, table_name, record_id, old_value, new_value, reason, timestamp)
VALUES ('UPDATE', 'equipment_battlegroup', 'GBR_ORDNANCE_QF_6-POUNDER_MK_V', 'NULL', '32', 'Tier 4: nation_caliber', datetime('now'));

-- Match 11/16: QF 17-pounder → 3" mortar
--   Caliber: 76mm
UPDATE equipment_battlegroup
SET reference_gun_id = 34,
    reference_gun_match_confidence = 90
WHERE equipment_id = 'GBR_QF_17-POUNDER';

-- Audit log
INSERT INTO normalization_audit (operation, table_name, record_id, old_value, new_value, reason, timestamp)
VALUES ('UPDATE', 'equipment_battlegroup', 'GBR_QF_17-POUNDER', 'NULL', '34', 'Tier 4: nation_caliber', datetime('now'));

-- Match 12/16: QF 6-pounder → 6 pdr
--   Caliber: 57mm
UPDATE equipment_battlegroup
SET reference_gun_id = 32,
    reference_gun_match_confidence = 90
WHERE equipment_id = 'GBR_QF_6-POUNDER';

-- Audit log
INSERT INTO normalization_audit (operation, table_name, record_id, old_value, new_value, reason, timestamp)
VALUES ('UPDATE', 'equipment_battlegroup', 'GBR_QF_6-POUNDER', 'NULL', '32', 'Tier 4: nation_caliber', datetime('now'));

-- Match 13/16: 17cm Kanone 18 → 170mmL50
--   Caliber: 170mm
UPDATE equipment_battlegroup
SET reference_gun_id = 10,
    reference_gun_match_confidence = 90
WHERE equipment_id = 'GER_17CM_KANONE_18';

-- Audit log
INSERT INTO normalization_audit (operation, table_name, record_id, old_value, new_value, reason, timestamp)
VALUES ('UPDATE', 'equipment_battlegroup', 'GER_17CM_KANONE_18', 'NULL', '10', 'Tier 4: nation_caliber', datetime('now'));

-- Match 14/16: 50mm Pak 38 → 50mm
--   Caliber: 50mm
UPDATE equipment_battlegroup
SET reference_gun_id = 2,
    reference_gun_match_confidence = 85
WHERE equipment_id = 'GER_50MM_PAK_38';

-- Audit log
INSERT INTO normalization_audit (operation, table_name, record_id, old_value, new_value, reason, timestamp)
VALUES ('UPDATE', 'equipment_battlegroup', 'GER_50MM_PAK_38', 'NULL', '2', 'Tier 4: nation_caliber_name', datetime('now'));

-- Match 15/16: Italian 20mm → 20mm
--   Caliber: 20mm
UPDATE equipment_battlegroup
SET reference_gun_id = 13,
    reference_gun_match_confidence = 85
WHERE equipment_id = 'GER_ITALIAN_20MM';

-- Audit log
INSERT INTO normalization_audit (operation, table_name, record_id, old_value, new_value, reason, timestamp)
VALUES ('UPDATE', 'equipment_battlegroup', 'GER_ITALIAN_20MM', 'NULL', '13', 'Tier 4: nation_caliber_name', datetime('now'));

-- Match 16/16: Italian 75mm → 75mm (IG18)
--   Caliber: 75mm
UPDATE equipment_battlegroup
SET reference_gun_id = 7,
    reference_gun_match_confidence = 85
WHERE equipment_id = 'GER_ITALIAN_75MM';

-- Audit log
INSERT INTO normalization_audit (operation, table_name, record_id, old_value, new_value, reason, timestamp)
VALUES ('UPDATE', 'equipment_battlegroup', 'GER_ITALIAN_75MM', 'NULL', '7', 'Tier 4: nation_caliber_name', datetime('now'));

-- Validation
SELECT COUNT(*) as tier4_artillery FROM equipment_battlegroup WHERE reference_gun_id IS NOT NULL;
-- Expected: 16

COMMIT;

-- Rollback if needed:
-- ROLLBACK;