#!/usr/bin/env node
/**
 * Equipment Research Helper
 *
 * Processes research requests generated by equipment_matcher_v2.py
 * Uses web search and source documents to find equipment data
 *
 * Usage:
 *   node tools/research_equipment.js <research_file>
 *
 * Example:
 *   node tools/research_equipment.js data/research_requests/french_french_canon_de_75_mle_1897_research.txt
 */

const fs = require('fs');
const path = require('path');

const researchFile = process.argv[2];

if (!researchFile) {
    console.error('Usage: node tools/research_equipment.js <research_file>');
    console.error('');
    console.error('Example:');
    console.error('  node tools/research_equipment.js data/research_requests/french_75mm_gun_research.txt');
    process.exit(1);
}

if (!fs.existsSync(researchFile)) {
    console.error(`ERROR: Research file not found: ${researchFile}`);
    process.exit(1);
}

// Read research request
const researchPrompt = fs.readFileSync(researchFile, 'utf-8');

console.log('='.repeat(80));
console.log('EQUIPMENT RESEARCH ASSISTANT');
console.log('='.repeat(80));
console.log('');
console.log(`Research file: ${researchFile}`);
console.log('');
console.log('This helper displays the research prompt for Claude Code.');
console.log('Copy and paste this into Claude Code to perform automated research.');
console.log('');
console.log('='.repeat(80));
console.log('RESEARCH PROMPT (copy everything below this line):');
console.log('='.repeat(80));
console.log('');
console.log(researchPrompt);
console.log('');
console.log('='.repeat(80));
console.log('');
console.log('Instructions:');
console.log('  1. Copy the research prompt above');
console.log('  2. Paste into Claude Code');
console.log('  3. Claude Code will use WebSearch and source documents');
console.log('  4. Save Claude\'s findings to update equipment database');
console.log('');
console.log('After research is complete:');
console.log('  - Update match_reviews table with findings');
console.log('  - Continue equipment matching session');
console.log('');
